# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marco Vinicius Soares Dalalba
email: vinisdl@hotmail.com  
keywords: "marco dalalba blog pessoal vinisdl dakn"
description: "Estudante de Ciências da computação, motociclista, apaixonado por desenvolvimento,
jogador nas horas vagas e não recusa um bom café."
baseurl: "" # the subpath of your site, e.g. /blog
phone: (51) 9663-7341
url: "http://www.marcodalalba.com" # the base hostname & protocol for your site
linkedin: vinisdl
twitter_username: vinisdl
github_username:  vinisdl
stack_overflow: http://pt.stackoverflow.com/users/59773/marco-vinicius-soares-dalalba
stack_overflow_theme: http://pt.stackoverflow.com/users/flair/59773.png?theme=clean
stack_overflow_alt_title: perfil de Marco Vinicius Soares Dalalba em Stack Overflow em Portugu&#234;s, Perguntas e respostas para programadores profissionais e entusiastas
google_analytics_key: UA-62899678-3 ## put YOUR key here to enable tracking! (blank to disable)

# Build settings
markdown: kramdown
