---
repository: sproogen/resume-theme
name: Marco Vinicius Soares Dalalba
title: Desenvolvedor Backend
email: vinisdl@hotmail.com
website: www.marcodalalba.com
google_analytics: UA-62899678-3
twitter_username: vinisdl
github_username: vinisdl
instagram_username: vinisdd
linkedin_username: vinisdl
about_title: Sobre Mim
about_profile_image: images/profile.jpg
about_content: |
  Desenvolvedor backend com 5 anos experiência em análise de sistemas e programação, cursando ciências da computação na Unisinos, com conhecimento sólido em aplicações web responsivas e escaláveis na nuvem.

  Eu sou muito bom em: <mark>C#</mark> e <mark>jogar CS</mark>


  Meu currículo completo <a href="https://github.com/vinisdl/resume/raw/master/Marco%20ViniciusSoares%20Dalalba.pdf"> Download </a>
skill_title: Skills
skill_time: anos
projects_title: Projetos
experience_title: Experiência
education_title: Educação
more_title: Um pouco mais sobre mim
more_content: 'Experiência na arquitetura de projetos escaláveis usando as principais
  linguagens e tecnologias do mercado, visando a qualidade e manutenibilidade

'
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
